deps: update Cypress 12.9.0 and cleaned up and pinned dependencies
* pinned "@types/lodash": "4.14.191", since version 4.14.192 results in error "cypress-ci-e2e.ts(88,46): error TS2769: No overload matches this call."
* removed now obsolete 'har-validator' (see cypress-io/cypress#19102)
* added package-lock.json to woked with a pinned dependencies set for e2e tests as well